In [1]:
import numpy as np

In [13]:
array = np.array([1, 3, 2, 4])

In [21]:
print(array)
print(np.sort(array))
print(array[0:2])
print(array[1:])
print(array[:4])

[1 3 2 4]
[1 2 3 4]
[1 3]
[3 2 4]
[1 3 2 4]


In [5]:
arr = np.arange(5)
print(arr)
# np.zeros zero array

[0 1 2 3 4]


In [43]:
arr = np.arange(2, 5, 0.5)# (start, end, step) end not included
print(arr)
arr1 = np.arange(-1, 1, 0.5)
print(arr1)

# evenly space items
x = np.linspace(4, 15, 15) # (start, stop(included) ,no of evenly sapced items)
print(x)

[2.  2.5 3.  3.5 4.  4.5]
[-1.  -0.5  0.   0.5]
[ 4.          4.78571429  5.57142857  6.35714286  7.14285714  7.92857143
  8.71428571  9.5        10.28571429 11.07142857 11.85714286 12.64285714
 13.42857143 14.21428571 15.        ]


In [8]:
for items in arr:
    print(items)

2.0
2.5
3.0
3.5
4.0
4.5


In [9]:
np.random.randint(2,10)

5

In [10]:
print(np.__version__)#checking numpy version

1.26.4


In [49]:
# numpy can use to increase memory efficiency
sample = np.random.randint(2,10, 2000000) # start, stop, quantity
sq_list = np.power(sample, 2)
print(sq_list)
print(len(sq_list))


# numpy can use rand function which means creating random values between zero and one
random_list = np.random.rand(1,5) # 1x5 matrix of random numbers (rows, columsn
print(random_list)

[16 49 49 ... 64 49  9]
2000000
[[0.09076589 0.4371511  0.95871283 0.28249999 0.89491609]]


# Dimensions

In [18]:
arr = np.array([1, 2, 3])
print(type(array))

<class 'numpy.ndarray'>


In [14]:
# finding dimensions
a = np.array(1) # zero dimension
b = np.array([1, 2])
c = np.array([[1, 2], [3, 4]])
print(a.ndim, b.ndim, c.ndim)
print(a, b, c)

0 1 2
1 [1 2] [[1 2]
 [3 4]]


In [34]:
# displaying 2D array using loops
arr = np.array([[1, 2], [3, 4]])
for x in arr:
    print(x)


[1 2]
[3 4]


In [20]:
    three_dimension = np.array([[[1, 2, 3], [7, 8, 9]], [[4, 5,6], [1, 2,3]]])
print(three_dimension.ndim, three_dimension)

3 [[[1 2 3]
  [7 8 9]]

 [[4 5 6]
  [1 2 3]]]


# Array by specifying Dimension

In [24]:
arr = np.array([1, 2, 3], ndmin=5)
print(arr, arr.ndim)

[[[[[1 2 3]]]]] 5


# *Shapes* 

In [34]:
arr_shape = np.array([[1, 2, 3], [3, 4, 5]])
print(arr_shape, arr_shape.shape) # (no of columns, no of rows)

[[1 2 3]
 [3 4 5]] (2, 3)


In [35]:
arr_shape.shape = (3, 2)
print(arr_shape, arr_shape.shape)

[[1 2]
 [3 3]
 [4 5]] (3, 2)


In [37]:
arr = np.array([[[1, 2, 3], [7, 8, 9]], [[4, 5,6], [1, 2,3]]])
reshaped_array = arr.reshape(2, 3, 2) #(dimensions, rows, columns)
print(reshaped_array)
# 4x3 = 12
# 2x6 = 12 
# we can reshape an array from 4x3 to 2x6

[[[1 2]
  [3 7]
  [8 9]]

 [[4 5]
  [6 1]
  [2 3]]]


# Make multidimensional 1 dimensional

In [38]:
arr = np.array([[[1, 2, 3], [7, 8, 9]], [[4, 5,6], [1, 2,3]]])
one_dim_arr = arr.reshape(-1)
print(one_dim_arr)

[1 2 3 7 8 9 4 5 6 1 2 3]


# Size

In [40]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
arr.itemsize

int32


4

In [44]:
arr = np.array([1, 2, 3, 4, 5], dtype='int16')
print(arr.dtype)
print(arr.itemsize) # size of one element in bytes int16
print(arr.size) # no of elements in array

int16
2
5


In [46]:
arr = np.array([1, 2, 3, 4, 5], dtype=complex)
print(arr.dtype)
print(arr.itemsize)
print(arr.size)
print(arr)

complex128
16
5
[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


# Type conversion

In [ ]:
arr = np.array([1.1, 10.2, 11.3])
conv = arr.astype('i')
print(conv)

ModuleNotFoundError: No module named 'matplotlib'

In [32]:
!pip3 install matplotlib

In [31]:
import numpy as np
import matplotlib.pyplot as plt

# Create a 2D NumPy array
data = np.random.rand(10, 10)

# Plot the 2D NumPy array
plt.imshow(data, cmap='viridis')  # cmap sets the color map
plt.colorbar()  # Add color bar indicating the scale
plt.xlabel('X-axis label')
plt.ylabel('Y-axis label')
plt.title('Title of the Plot')
plt.show()

ModuleNotFoundError: No module named 'matplotlib'

# Mathematical operations on array

In [24]:
arr = np.array([1, 2, 3 , 4, 5])
print(arr + 5)
# any mathematical operation on array results in similiar operation with all elements in array

[ 6  7  8  9 10]


# searching

In [25]:
arr = np.array([1, 2, 3 , 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)
# np.where returns another list of indices where a special value find

(array([3, 5, 6], dtype=int64),)


# indcies where values are even

In [27]:
arr = np.array([1, 2, 3 , 4, 5, 4, 4])
x = np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 6], dtype=int64),)


# Other operations

In [30]:
# filtering by using an boolean index list
arr = np.array([1,2,3,4])
bool = np.array([True, False, True, False])
x = arr[bool] # by doing this elments corresponding with true are displayed in resultant array only
print(x)

[1 3]


In [51]:
# eye (identity matrix)
x = np.eye(5)
y = np.eye(5,3) # (rows, columns)
print(x)
print(y)

# diagonal matrix
diag_matrix = np.diag([1,2,3])
print(diag_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [53]:
# flatten a matrix
# simple method to transform any array to 1D array
arr = np.array([[1,2,3,4], [123,22,33,4], [1,22,34,4]])
arr_flatten = arr.flatten()
print(arr_flatten)

[  1   2   3   4 123  22  33   4   1  22  34   4]


In [59]:
# trace = sum of diagonal elements
arr = np.array([[1,2,3,4], [123,22,33,4], [1,22,34,4]])
trace = arr.trace()
print(trace)
print(arr.diagonal())
print(sum(arr.diagonal()))

57
[ 1 22 34]
57


In [61]:
arr = np.array([[1,2,3,4], [123,22,33,4], [1,22,34,4]])
transpose = np.transpose(arr)
transpose

array([[  1, 123,   1],
       [  2,  22,  22],
       [  3,  33,  34],
       [  4,   4,   4]])